### ISSUE TITLE
Annotation

### ISSUE THREAD

**Issue by priyambial123** [amwenger/svpack#12]
Hello

I used sv package (https://github.com/PacificBiosciences/svpack to annotate the structural variants). What does SVANN:Tandem mean in the annotation? Does it mean the variant is present in the repeat region?

Thanks

**Comment by amwenger** [comment]
Yes, `SVANN` means that the variant is a tandem repeat expansion or contraction.  `svpack` does not add `SVANN` annotation, but it will process that annotation from `pbsv`

**Comment by priyambial123** [comment]
Thank you
