### ISSUE TITLE
Question for installation

### ISSUE THREAD

**Issue by dbswls0322** [amwenger/svpack#14]
Dear Pacbio developer.

 I'm deeply eager to analyze hifi WGS data before generating data.
 I wonder how I can install "svpack" package on my own.
 
 Even I looked up every section on your github, I couldn't find how to install.
 Is it already belong to other package?

 Please inform me about installation.
 
 Best Regards.

**Comment by williamrowell** [comment]
Hello,

`svpack` is a python script with only one dependency (`pysam`) outside of the standard python libraries.

- download the script; you can do this either by cloning the repo or by directly downloading the svpack script
  ```bash
  # EITHER
  # clone the repository
  git clone https://github.com/PacificBiosciences/svpack.git
  # the svpack script will be inside of the svpack folder that was just created

  # OR directly download the script with wget
  wget https://raw.githubusercontent.com/PacificBiosciences/svpack/main/svpack
  # OR directly download the script with curl
  curl -O https://raw.githubusercontent.com/PacificBiosciences/svpack/main/svpack
  ```
- set up the dependencies; typically people install non-standard libraries with either conda or pip; typically you want to set up a [virtual environment](https://realpython.com/python-virtual-environments-a-primer/) to contain these dependencies, but that's beyond the scope of this help message
  ```bash
  # EITHER
  # install pysam with pip
  python3 -m pip install pysam

  # OR install pysam with conda
  conda config --add channels defaults
  conda config --add channels bioconda
  conda config --add channels conda-forge
  conda config --set channel_priority strict
  conda install pysam
  ```
- now you should be able to run `svpack`

If you have any more questions, please reach out to support@pacb.com.

**Comment by dbswls0322** [comment]
Thank you so much for your detailed explanation.
 Let me try it.

 Have a good day!
