### ISSUE TITLE
Where can download "HPRC_GIAB.GRCh38.pbsv.vcf.gz" file?

### ISSUE THREAD

**Issue by DayTimeMouse** [amwenger/svpack#16]
Hi,

Where can download "HPRC_GIAB.GRCh38.pbsv.vcf.gz" file?

I used pbsv to get sv.vcf.gz. Can I extract the FILTER=pass variants form vcf file as confident variants? Is it OK？

Best wishes.

**Comment by amwenger** [comment]
> Where can download "HPRC_GIAB.GRCh38.pbsv.vcf.gz" file?

The data resources are available in a `.tgz` file at https://doi.org/10.5281/zenodo.8415406. HPRC population VCF is at `static_resources/GRCh38/sv_pop_vcfs/hprc.GRCh38.pbsv.vcf.gz`

```
# Download and untar
$ curl --output "wdl-humanwgs.v1.0.2.resource.tgz" "https://zenodo.org/records/8415406/files/wdl-humanwgs.v1.0.2.resource.tgz?download=1"
$ tar -xzvf wdl-humanwgs.v1.0.2.resource.tgz
```


> I used pbsv to get sv.vcf.gz. Can I extract the FILTER=pass variants form vcf file as confident variants? Is it OK？

Yes, we typically use the `PASS` variants from SV callers.
