### ISSUE TITLE
Inquiry for annotation file

### ISSUE THREAD

**Issue by dbswls0322** [amwenger/svpack#17]
Dear Pacbio developer.

First of all, I appreciate your previous help for installation of package.
I faced one problem again to run the code.

I downloaded tgz file and unzip it following the indication uploaded in github

curl --output "wdl-humanwgs.v1.0.2.resource.tgz" "https://zenodo.org/records/8415406/files/wdl-humanwgs.v1.0.2.resource.tgz?download=1"
tar -xzvf wdl-humanwgs.v1.0.2.resource.tgz

Then, I ran my code below.

zcat HCC1395.GRCh38.pbsv.phased.chr1.vcf.gz     |           
  ./svpack filter --pass-only --min-svlen 50 -   |                       
  ./svpack match -v - HCC1395-BL.GRCh38.pbsv.phased.chr1.vcf.gz |          
  ./svpack consequence --require-csq -  \
      <(zcat ../static_resources/GRCh38/ensembl.GRCh38.101.reformatted.gff3.gz) |       
  grep  "sv:cds" | cut -f1-3,8          

And I got this error since I've tried svpack.

**gzip: ../static_resources/GRCh38/ensembl.GRCh38.101.reformatted.gff3.gz: not in gzip format**

Even though I downloaded and tried to unzip it manually, still failed.

![image](https://github.com/user-attachments/assets/8bea70af-f67d-4ad0-9fe8-fcbb41ca5f61)

Can you check whether this file is available and let me know where I can download the clear data? 

Best Regards.

**Comment by williamrowell** [comment]
Despite the file extension on the gff, it is not compressed.  There's no need to uncompress it.  Try something like:

```bash
zcat normal.vcf.gz \
  | ./svpack filter --pass-only --min-svlen 50 - \
  | ./svpack match -v - tumor.vcf.gz \
  | ./svpack consequence --require-csq - ensembl.GRCh38.101.reformatted.gff3.gz \
  | grep "sv:cds" | cut -f1-3,8
```
