### ISSUE TITLE
Required INFO fields for match

### ISSUE THREAD

**Issue by gungorbudak** [amwenger/svpack#5]
It seems `match` requires following INFO fields: `SVTYPE`, `SVLEN` and `END`(I'm not sure if all are required or there are more) but Delly doesn't report `SVLEN`. It could be useful if `SVLEN` can be inferred if not present by taking `POS - END` or 
`LENGTH(ALT) - LENGTH(REF)`. This might make `svpack` directly compatible with Delly outputs. I also tried Manta and it works with Manta.

**Comment by amwenger** [comment]
Thanks for the suggestion, @gungorbudak.  I implemented your suggestion in 47c65c7, which is now in the main branch.  The SV length is now obtained, in precedence order from:
1. SVLEN INFO field
2. LENGTH(ALT) - LENGTH(REF) for INS and DEL
3. `END - POS + 1` when END is specified

Does that work as you had hoped?

**Comment by gungorbudak** [comment]
Thanks @amwenger, this works! Except I had to wrap the return values of `get_svlen()` with `abs()`s because for some reason Manta outputs `SVLEN` as a negative value which causes `ZeroDivisionError` below in the lengths in A and B are the same and otherwise no match can be found. So if you think it makes sense, you might want to add `abs()` as well.

```
Traceback (most recent call last):
  File "/Users/gungor/Desktop/simons/./svpack", line 690, in <module>
    main()
  File "/Users/gungor/Desktop/simons/./svpack", line 686, in main
    args.func(args)
  File "/Users/gungor/Desktop/simons/./svpack", line 240, in match_main
    0 if svlen_diff == 0 else 2 * svlen_diff / (Asvlen + Bsvlen)
ZeroDivisionError: division by zero
```

Manta line in my example:
```
chr20	21869264	MantaDEL:0:0:0:0:0:0	GTCTTTACATCTGTTGAAATCAGGAAGTAACTGGAATTCACAAATTTCTGGTCACTTGAGATTTCCTGACTGTTTTATGAACCACAGTTGAACATAAATTAATCTTGGGAACATACTGGAGTTTACTTGTGTCTCTAGACCATTTTATAGCCCAGATCTTTTCCTGAAAGATGGCTTTGCTGTTGATTTCCACTTTCCTTAGGATCTTTACAGAAACTTCTCCAGCTTCTGAAAGGGCCAGAAGAATTTACCTGTCTGAAAGCAGAGGTCACACATGAATGGAATGAA	G	999	PASS	END=21869551;SVTYPE=DEL;SVLEN=-287;CIGAR=1M287D;CIPOS=0,1;HOMLEN=1;HOMSEQ=T	GT:FT:GQ:PL:PR:SR	1/1:PASS:71:999,74,0:0,18:0,25
```

Delly line:
```
chr20	21869264	DEL00000001	G	<DEL>	960	PASS	PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.8.7;END=21869552;PE=0;MAPQ=0;CT=3to5;CIPOS=-2,2;CIEND=-2,2;SRMAPQ=60;INSLEN=0;HOMLEN=2;SR=16;SRQ=0.992;CONSENSUS=TGCCTTGAACATTAAGATTGTTAATTTGAGTGTGGGGAAAAACTAATCTAATACTCATTTCAGTGAGTGTCCAATGATAGAGGATGTGAGCCACTAGGAATATTCTGTAATCAAATGTAGATATG;CE=1.90527	GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV	1/1:-86.7896,-8.41845,0:84:PASS:4193:38:5054:0:0:0:0:28
```

**Comment by amwenger** [comment]
Thanks for the example, @gungorbudak.  I pushed another update that now compares `|SVLEN|` instead of the signed `SVLEN`; so, you should be able to use the main branch.  Per the [VCF specification](https://samtools.github.io/hts-specs/VCFv4.3.pdf), it is correct for `SVLEN` to be negative for deletions.  In other words, Manta has it correct.  But since `svpack match` only compares variants of the same type (i.e. DEL to DEL, INS to INS); it is fine to compare `|SVLEN|` to be robust to how it is represented in the SV caller.

The relevant portion of the VCF specification is:
> ```##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">```
> 
> One value for each ALT allele. Longer ALT alleles (e.g. insertions) have positive values, shorter ALT alleles (e.g. deletions) have negative values.
