### ISSUE TITLE
svpack consequence removing END

### ISSUE THREAD

**Issue by fakedrtom** [amwenger/svpack#7]
I've been trying to use svpack consequence to add genic annotations to my SVs. When trying to do this with Manta VCFs, I am noticing that on some occasion the END from the INFO field looks to be removed after running svpack. For example, here is the INFO field for a Manta DEL before svpack:
```
END=1226400;SVTYPE=DEL;SVLEN=-64;CIGAR=1M1I64D
```
And here is the same DEL after running svpack:
```
SVTYPE=DEL;SVLEN=-64;CIGAR=1M1I64D;BCSQ=sv:intron|SDF4||protein_coding|-||
```
As best I can tell this only seems to happen in the event of a smaller SVs where the REF and ALT list the actual sequence changes, but when ALT is DEL or INS, the END is included after running svpack, as I would expect. Is there a reason why END should be removed under certain conditions? I have only observed this in the case of DELs and INSs. not DUPs (DUPs seem to always list an ALT of DUP rather than actual sequence).

I have also tested this on a VCF produced using Lumpy and I do not see this happening there. So far it seems to be specific to Manta calls.

**Comment by amwenger** [comment]
Thanks for reporting.   This behavior is inherited from pysam, which `svpack` uses to read, manipulate, and write VCF records.  See https://github.com/pysam-developers/pysam/issues/659.

I found a workaround, which is applied in 595c2e4.
